
#import <Foundation/Foundation.h>

#import <CFGameSDK/ZKBaseDefine.h>

/**
 * This is the main assert macro that you should use. Asserts should be compiled out
 * in production builds. You can customize the assert behaviour by setting a custom
 * assert handler through `KCSetAssertFunction`.
 */
#ifndef NS_BLOCK_ASSERTIONS
#define ZKAssert(condition, ...) do { \
  if ((condition) == 0) { \
    _ZKAssertFormat(#condition, __FILE__, __LINE__, __func__, __VA_ARGS__); \
    if (ZK_NSASSERT) { \
      [[NSAssertionHandler currentHandler] handleFailureInFunction:@(__func__) \
        file:@(__FILE__) lineNumber:__LINE__ description:__VA_ARGS__]; \
    } \
  } \
} while (false)
#else
#define ZKAssert(condition, ...) do {} while (false)
#endif
ZK_EXTERN void _ZKAssertFormat(
  const char *, const char *, int, const char *, NSString *, ...
) NS_FORMAT_FUNCTION(5,6);

/**
 * Report a fatal condition when executing. These calls will _NOT_ be compiled out
 * in production, and crash the app by default. You can customize the fatal behaviour
 * by setting a custom fatal handler through `KCSetFatalHandler`.
 */
ZK_EXTERN void ZKFatal(NSError *error);

/**
 * The default error domain to be used for React errors.
 */
ZK_EXTERN NSString *const ZKErrorDomain;

/**
 * JS Stack trace provided as part of an NSError's userInfo
 */
ZK_EXTERN NSString *const ZKJSStackTraceKey;

/**
 * Name of fatal exceptions generated by KCFatal
 */
ZK_EXTERN NSString *const ZKFatalExceptionName;

/**
 * A block signature to be used for custom assertion handling.
 */
typedef void (^ZKAssertFunction)(
                                  NSString *condition,
                                  NSString *fileName,
                                  NSNumber *lineNumber,
                                  NSString *function,
                                  NSString *message
                                  );

typedef void (^ZKFatalHandler)(NSError *error);

/**
 * Convenience macro for asserting that a parameter is non-nil/non-zero.
 */
#define ZKAssertParam(name) ZKAssert(name, @"'%s' is a required parameter", #name)

/**
 * Convenience macro for asserting that we're running on main thread.
 */
#define ZKAssertMainThread() ZKAssert([NSThread isMainThread], \
  @"This function must be called on the main thread")

/**
 * Convenience macro for asserting that we're running off the main thread.
 */
#define ZKAssertNotMainThread() ZKAssert(![NSThread isMainThread], \
@"This function must not be called on the main thread")

/**
 * These methods get and set the current assert function called by the KCAssert
 * macros. You can use these to replace the standard behavior with custom assert
 * functionality.
 */
ZK_EXTERN void ZKSetAssertFunction(ZKAssertFunction assertFunction);
ZK_EXTERN ZKAssertFunction ZKGetAssertFunction(void);

/**
 * This appends additional code to the existing assert function, without
 * replacing the existing functionality. Useful if you just want to forward
 * assert info to an extra service without changing the default behavior.
 */
ZK_EXTERN void ZKAddAssertFunction(ZKAssertFunction assertFunction);

/**
 * This method temporarily overrides the assert function while performing the
 * specified block. This is useful for testing purposes (to detect if a given
 * function asserts something) or to suppress or override assertions temporarily.
 */
ZK_EXTERN void ZKPerformBlockWithAssertFunction(void (^block)(void), ZKAssertFunction assertFunction);

/**
 These methods get and set the current fatal handler called by the KCFatal method.
 */
ZK_EXTERN void ZKSetFatalHandler(ZKFatalHandler fatalHandler);
ZK_EXTERN ZKFatalHandler ZKGetFatalHandler(void);

/**
 * Get the current thread's name (or the current queue, if in debug mode)
 */
ZK_EXTERN NSString *ZKCurrentThreadName(void);

/**
 * Helper to get generate exception message from NSError
 */
ZK_EXTERN NSString *ZKFormatError(NSString *message, NSArray<NSDictionary<NSString *, id> *> *stacktrace, NSUInteger maxMessageLength);

/**
 * Convenience macro to assert which thread is currently running (DEBUG mode only)
 */
#if DEBUG

#define ZKAssertThread(thread, format...) \
_Pragma("clang diagnostic push") \
_Pragma("clang diagnostic ignored \"-Wdeprecated-declarations\"") \
ZKAssert( \
  [(id)thread isKindOfClass:[NSString class]] ? \
    [ZKCurrentThreadName() isEqualToString:(NSString *)thread] : \
    [(id)thread isKindOfClass:[NSThread class]] ? \
      [NSThread currentThread] ==  (NSThread *)thread : \
      dispatch_get_current_queue() == (dispatch_queue_t)thread, \
  format); \
_Pragma("clang diagnostic pop")

#else

#define ZKAssertThread(thread, format...) do { } while (0)

#endif
